### ISSUE TITLE
Install OpenMAINT on Windows 11 attempt

### ISSUE THREAD

**Issue by kurtzace** [kurtzace/Diary2021#19]
1. Install chocolatey from https://chocolatey.org/install
2. Run powershell.exe by typing Windows+R key and typing powershell

![image](https://user-images.githubusercontent.com/2136211/182023967-d15bc581-4478-4010-8018-b4226fdbc455.png)
![image](https://user-images.githubusercontent.com/2136211/182023942-30f31157-204e-45b2-96a2-12139ae29013.png)

3. Right click powershell icon and run as admin 
![image](https://user-images.githubusercontent.com/2136211/182024046-798bfef4-fdce-4abd-8ffc-ee4c771b915d.png)
4. Go to relevant directory - run the following
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```
You will see success message like
![image](https://user-images.githubusercontent.com/2136211/182024107-1b41ddce-5f27-4d2e-a940-b88d885d9935.png)

5. close powershell and reopen in admin mode
6. Type the following to see if choco works
```
choco --v
```
should not echo error
7. Install jdk11 - type following in powershell
```
choco install openjdk11 -y
```
8. Install postgre sql
```
choco install postgresql
```
type 'A' to accept all

you will see generated password, note it down
![image](https://user-images.githubusercontent.com/2136211/182027717-45aacfe8-1ee1-4136-9daf-7f9f853f6840.png)

If you still miss it - go to "C:\ProgramData\chocolatey\logs\chocolatey.log"

and search for 'Generated password'

note path of success

example 'C:\Program Files\PostgreSQL\14'

add to path
![image](https://user-images.githubusercontent.com/2136211/182027382-48d573bf-0a23-4763-bad7-e043d75cf797.png)

9. Download openMAINT [openMAINT](https://sourceforge.net/projects/openmaint/files/2.1/Core%20updates/openmaint-2.1-3.3.2/openmaint-2.1-3.3.2.war) and place it in the same path as powershell prompt

![image](https://user-images.githubusercontent.com/2136211/182026342-08d98c2e-c116-4494-b60a-d66ca6cd369f.png)

I typed `ls | grep open` to see if file was downloaded well.

10.  Test installations
a. Java ` java -version`
``` 
PS D:\Softwares\programming> java -version
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

b. Test Postgres
restart powershell
test Postgres
```
$Env:PGPASSWORD='.....generated password.....'
psql -h localhost -p 5432 -d postgres  -U postgres
```
you will see
![image](https://user-images.githubusercontent.com/2136211/182027058-2d896779-81e4-4fa6-9045-ed0387a511f8.png)
type `exit`

11. install openMAINT
```
java -jar ./openmaint-2.1-3.3.2.war install
```

answer the questions

![image](https://user-images.githubusercontent.com/2136211/182027871-193f3c70-3ff4-4535-b73e-1993ddc41142.png)

I see error

![image](https://user-images.githubusercontent.com/2136211/182028022-73d1f96c-054b-4f92-a3a8-1d3698612366.png)

google that error

https://gis.stackexchange.com/questions/71302/running-create-extension-postgis-gives-error-could-not-open-extension-control-fi

from there go to 

https://postgis.net/windows_downloads/

then to 

http://download.osgeo.org/postgis/windows/

go to pg14

![image](https://user-images.githubusercontent.com/2136211/182028152-77d7feaa-bead-4bcf-bdbe-bc04c583bfd2.png)

download "postgis-bundle-pg14x64-setup-3.2.1-1.exe"

I choose defaults including postgres location

![image](https://user-images.githubusercontent.com/2136211/182028223-025e03de-2533-4f3a-9578-a91234209802.png)

rerun openMaint

new error is

```
if everything is ok, press ENTER to begin installation
<press enter to begin>
BEGIN installation
install tomcat...
OK
create database...
create database cmdbuild_d735 demo.dump.xz
Exception in thread "main" org.cmdbuild.dao.DaoException: Error while configuring the database
        at org.cmdbuild.dao.config.inner.DatabaseCreator.configureDatabase(DatabaseCreator.java:201)
        at org.cmdbuild.utils.cli.utils.DatabaseUtils.createDatabase(DatabaseUtils.java:42)
        at org.cmdbuild.utils.cli.utils.DatabaseUtils.createDatabase(DatabaseUtils.java:36)
        at org.cmdbuild.utils.cli.utils.DatabaseUtils.createDatabase(DatabaseUtils.java:32)
        at org.cmdbuild.utils.cli.commands.InstallCommandRunner.exec(InstallCommandRunner.java:167)
        at org.cmdbuild.utils.cli.commands.AbstractCommandRunner.exec(AbstractCommandRunner.java:80)
        at org.cmdbuild.utils.cli.Main.runMain(Main.java:129)
        at org.cmdbuild.utils.cli.Main.main(Main.java:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.cmdbuild.webapp.cli.Main.runCli(Main.java:125)
        at org.cmdbuild.webapp.cli.Main.startFromWarFile(Main.java:89)
        at org.cmdbuild.webapp.cli.Main.main(Main.java:37)
Caused by: org.cmdbuild.dao.DaoException: java.lang.RuntimeException: unable to find working psql version for this postgres server
        at org.cmdbuild.dao.config.inner.DatabaseCreator.restoreDump(DatabaseCreator.java:409)
        at org.cmdbuild.dao.config.inner.DatabaseCreator.configureDatabase(DatabaseCreator.java:185)
        ... 14 more
Caused by: java.lang.RuntimeException: unable to find working psql version for this postgres server
        at org.cmdbuild.utils.lang.CmExceptionUtils.runtime(CmExceptionUtils.java:64)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.runCommand(PostgresHelperImpl.java:379)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.restoreDumpFromFile(PostgresHelperImpl.java:238)
        at org.cmdbuild.utils.postgres.PostgresHelper.restoreDumpFromFile(PostgresHelper.java:50)
        at org.cmdbuild.dao.config.inner.DatabaseCreator.restoreDump(DatabaseCreator.java:377)
        ... 15 more
Caused by: java.lang.RuntimeException: command psql return error code = 2 : psql: FATAL: password authentication failed for user "shark"
        at org.cmdbuild.utils.lang.CmExceptionUtils.runtime(CmExceptionUtils.java:68)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.runCommand(PostgresHelperImpl.java:392)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.executeQuery(PostgresHelperImpl.java:246)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.getServerVersion(PostgresHelperImpl.java:128)
        at org.cmdbuild.utils.postgres.PostgresHelperImpl.runCommand(PostgresHelperImpl.java:357)
        ... 18 more
PS D:\Softwares\programming>
```

need to google above error and continue solving

11. b. if I ignore above error and see if I can proceed further

go to  %USERPROFILE%\cmdbuild_30_3\bin
![image](https://user-images.githubusercontent.com/2136211/182028801-b59d7305-92f0-40a0-9563-ee0dc872f908.png)

a. open powershell here

![image](https://user-images.githubusercontent.com/2136211/182028836-ee2de29a-420f-44c2-9263-dd332c77ac0c.png)

type .\startup.bat

allow access
![image](https://user-images.githubusercontent.com/2136211/182028859-84e496f4-3604-4f89-944a-cb0306375920.png)

 you will see tomcat window open
![image](https://user-images.githubusercontent.com/2136211/182028881-e21612a0-b468-4e9b-bd84-55dd98a38a47.png)

open 

`http://localhost:8080/cmdbuild/`

in webbrowser

you will see

![image](https://user-images.githubusercontent.com/2136211/182028967-31538466-ab91-49a1-aa88-8293761001b3.png)

it will force you to apply patches

and it will fail
![image](https://user-images.githubusercontent.com/2136211/182029011-7f881d53-0cc7-464c-9d4e-b432601706fa.png)

13. ALTERNATELY now will try newer or older version of Openmaint 2.2
https://sourceforge.net/projects/openmaint/files/latest/download
unzip and 
```
 java -jar .\openmaint-2.2-3.4.war install
```

got below error
```
PS D:\Softwares\programming\openmaint-2.2-3.4> java -jar .\openmaint-2.2-3.4.war install
Error: LinkageError occurred while loading main class org.cmdbuild.webapp.cli.Main
        java.lang.UnsupportedClassVersionError: org/cmdbuild/webapp/cli/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
```

maybe upgrading java may help

## references
- https://techviewleo.com/how-to-install-openmaint-on-debian-10-buster/
- https://community.chocolatey.org/packages/postgresql and https://www.sqlshack.com/how-to-install-postgresql-on-windows/ and https://www.enterprisedb.com/postgres-tutorials/connecting-postgresql-using-psql-and-pgadmin

**Comment by kurtzace** [comment]
## ubuntu
```
sudo apt install openjdk-17-jre-headless 
```
